version: '3.2'
services:
  generate-gif:
    build: ./generate-gif
    ports:
      - '3003:3003'
    environment:
      GENERATE_GIF_PORT: 3003
    restart: always
    volumes:
      - type: bind
        source: ///c/Users/gif/camera_output
        target: /app/camera_output
      - type: bind
        source: ./gifs
        target: /app/gifs
  app:
    build: .
    ports:
      - '3002:3002'
    environment:
      WEB_APP_PORT: 3002
      CAMERA_OUTPUT: camera_output
    restart: always
  send-gifs:
    build: ./send-gifs
    restart: always
    volumes:
      - type: bind
        source: ./gifs
        target: /app/gifs
